travis:
  secure:
    BINSTAR_TOKEN: LTd1G67EYvlhkQqBqKZMlNVkAqNg6XlJ9aiPPLeoIplgnHxt97OL2UedIgGUDRX9tXBFzU7HbdUbyE6f5vO3U5yEfY9K560JCdIwFrlJSI5jIwS68KxXST3U3kMleEP811xiBLLuO7K9ClrrJMWEhM5VdLEDoLpIuakugKjlXsZjTSKjTulWk+Ox7wjnTcH5Y5ILYcpAAwqstpr881QeCjMK2MyE7eQewokqF3fQFHKVmvTklnMHv/bYZOIObM/8rg8uabb3qA5Hy37poqJyjza7UKTIbXOT0PQClmXMG9bskl52cJTlXEY5lfEbQGWP4uGtQdPkk2Od9LlOSA0r8/jPafkf5WEaPINCetUDbzyVRI33+9n6NVZTlN1vQbxW4EANs1ulylbNW52mKTr/7vYvMCQLnkKgCgIo5XZS17iBn+6vykgRcygUwfuBhblMhaLUyfr/4iGSil1EZ4cembsN4IsNHCHARWXq+94OyoAJYEqk+V1rYxEt1jXBD6huAOVMM7tz3YHSgW1kzHrbhsJKttilZfdpCp6AjsJ43TisWkmX9VD350KhWV5C6jfczHA0aClDGNERhKV21xKwIXK9jxEaNONbChMm+yywoxOepAK2IrPxOt3LOdxatlxij0hnR5/pBZbh3079SAqnD8yM2QRjOaSmBzxeiBCfOk0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
